### PR TITLE
Merge Channels, Tutorials, and Courses to Education

### PR DESCRIPTION
**Pull request by julianrubisch**
This is just a proposal to merge the Channels, Tutorials, and Courses model into a single "Education" page to slim down the navigation a bit.

I also took the liberty to add https://www.patreon.com/TheHotwireClub, and insert all the courses, since AFAIK they weren't yet listed anywhere.

Open for debate!

### CODE REVIEW

**Comment by marcoroth** [comment]
Thanks for this @julianrubisch! I like the idea of combining them into a `Education` section. 

I'm wondering if it would make sense to have a section for "Communities" where we are highlight communities like your Hotwire club on Patreon, Discord servers, and other forums like the official Hotwire Discourse and collect them in a `communities.yml` file.

Does that make sense?

**Comment by julianrubisch** [comment]
Yeah totally. I just thought that Community > Communities would read weirdly ...

**Comment by marcoroth** [comment]
Maybe "Online Communities" would make more sense?

**Comment by marcoroth** [comment]
@julianrubisch happy to merge this one if you can update the PR and resolve the conflicts 🙌🏼

**Comment by julianrubisch** [comment]
done!

**Review by marcoroth — APPROVED** [review]
Thanks!

**Pull request merged**
