### PR TITLE
Better attempt at making links on UseCases pages clickable

### PR DESCRIPTION
**Pull request by infews**
Using SitePress patterns:

- Adds a Ruby model for Animations `UseCases::Animation` (as an example)
- Adds a directory for the various UseCases pages under `app/content/data`
- Moves the URLs from the view to the data yaml

If we like this, I can do the same for the rest of the UseCases.

Future Suggestions
- Add list-type back so the bullets are shown
- Add optional text about each link? Maybe?

### CODE REVIEW

**Comment by marcoroth** [comment]
I like the idea where this is going @infews! Also makes we want if we can actually re-use the same view for all the pages 👀

**Comment by infews** [comment]
Cool! I'll finish off this pattern for the other pages. Then I'll see if I can make a single view.

**Comment by infews** [comment]
@marcoroth This branch moves all of the UseCases to YML-backed. Sorry for the size of the commit!

I'm going to use this as a basis for a follow-on PR that can (optionally) reduce this to a single component. Stay Tuned!

**Review by marcoroth — APPROVED** [review]
Thank you so much @infews! This is great change in the right direction!

I just pushed some smaller things I noticed while reviewing, but all good, thank you!

**Comment by marcoroth** [comment]
Regarding your future suggestions:

Yeah, I think we need something more appealing! I was thinking of having cards, with an image, headline and small description each for each link. Similar to this:

image

**Pull request merged**
