### PR TITLE
Update favicon for higher resolutions

### PR DESCRIPTION
**Pull request by connorbey13**
- Generated higher resolution icons and webmanifest that support multiple browsers at [https://favicon.io/favicon-converter/](https://favicon.io/favicon-converter/) with the image from [https://github.com/marcoroth/turbo_power/blob/main/assets/icon.png](https://github.com/marcoroth/turbo_power/blob/main/assets/icon.png).
- Replaced favicon text in head with text from the generator.
- Removed unneeded file `apple-touch-icon-precomposed.png`.

### CODE REVIEW

**Comment by marcoroth** [comment]
Thanks for this, @connorbey13!

Though, I don't think it makes sense to use the Turbo Power icon for the Hotwire.io website. Would you mind doing the using the regular Hotwire icon?

**Comment by connorbey13** [comment]
Agreed! Updated.

**Comment by marcoroth** [comment]
We had to remove the official assets, so we sadly have to close this one for now. Thanks for working on this @connorbey13!

**Comment by marcoroth** [comment]
Though, we could use the Turbo Power logo with the higher resolutions instead

**Pull request closed without merging**
