### PR TITLE
Rails installation using importmaps

### PR DESCRIPTION
**Pull request by sebscholl**
Initial guide for explaining the setup of import maps in Rails.

### CODE REVIEW

**Comment by marcoroth** [comment]
Hey @sebscholl, thank you so much for working on this!

Just curious, is this derived from the importmap-rails README? If so, we should maybe declare it as such.

**Comment by sebscholl** [comment]
No problem @marcoroth . I wrote this while testing the `rails importmap:install`. That said, I'll update the guide with a reference to the Working with Javascript in Rails guide (https://guides.rubyonrails.org/working_with_javascript_in_rails.html)

**Review by marcoroth — APPROVED** [review]
Thank you @sebscholl! 🙏🏼

**Comment by sebscholl** [comment]
Happy to help.

**Pull request merged**
