### PR TITLE
Improve Frameworks Page

### PR DESCRIPTION
**Pull request by pkayokay**
Improves the overall look of the frameworks page, also adds a logo and descriptions to each item. Closes https://github.com/marcoroth/hotwire.io/issues/33

## Before
image

### Desktop
desktop

### Smaller desktop
between

### Mobile
mobile

### CODE REVIEW

**Comment by pkayokay** [comment]
Should the framework model be ordered alphabetically?

**Review by marcoroth — COMMENTED** [review]
Nice! Thanks @pkayokay, this looks great!

> Should the framework model be ordered alphabetically?

I think that would make sense, yes!

I was also wondering if we might be able to upstream some of those framework icons directly to the iconfont itself. But for now to keep it simple, we can keep it like this.

Would you mind updating the icons in the `app/views/application/home/_integrations.html.erb` file as well. That would be great, thank you!

Otherwise this looks good to me!

**Comment by marcoroth** [comment]
Oh right, then let's just update the Bridgetown one.

**Comment by pkayokay** [comment]
image

**Review by marcoroth — APPROVED** [review]
This is awesome, thank you so much for this @pkayokay!

**Comment by AhmedNadar** [comment]
Oh man @pkayokay you are ahead of me, but you beat me to it 👍🏼 😄 
I'm working on it and my version is so close to your. Well done Paul, looks awesome.

**Pull request merged**
